######### NORMAL OPERATION  ###########
@baseUrl = http://localhost:3000

### Read all texts with File variable
GET {{baseUrl}}/texts

### Read all texts sorted level hard
GET {{baseUrl}}/texts/?level=hard

### Read all texts sorted level easy
GET {{baseUrl}}/texts/?level=easy

### Read a text
GET {{baseUrl}}/texts/d14c4966-9615-4519-bd08-ca77d9d4df0f

### Create a texts
POST {{baseUrl}}/texts
Content-Type: application/json

{
    "content":"test",
    "level":"hard"
}

### Delete texts identified by 2
DELETE {{baseUrl}}/texts/9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d

### Try to update text with missing param
PUT {{baseUrl}}/d3f1855e-6131-407f-80e8-e52173b88627
Content-Type: application/json

{
    "content":"oh i am missing the level..."
}