### Read all film with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films

### Read all films sorted by title (minimum 120)
GET {{baseUrl}}/films?duration=120

### Create a film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title":"Harry Potter et la coupe de feu",
    "duration": 143,
    "budget": 190,
    "link":"google.com"
}

### Update a film
PATCH {{baseUrl}}/films/1
Content-Type: application/json

{
    "title":"Harry Potter et les reliques de la mort",
    "duration": 143,
    "budget": 190,
    "link":"google.com"
}

### Delete film identified by id
DELETE {{baseUrl}}/films/6

### Update one or create one
PUT {{baseUrl}}/films/7
Content-Type: application/json

{
    "title":"Harry Potter et les reliques de la mort 2",
    "duration": 143,
    "budget": 190,
    "link":"google.com"
}

